### ISSUE TITLE
ERROR [templating-resources]

### ISSUE THREAD

**Issue by ghost** [adarshpastakia/aurelia-ui-framework#102]
`ERROR [templating-resources] Error: Unable to find module with ID: aurelia-ui-framework/elements/core/ui-glyphs
`

**Comment by adarshpastakia** [comment]
@sackery are you using webpack?

**Comment by ghost** [comment]
@adarshpastakia yes, should i use requirejs?

**Comment by adarshpastakia** [comment]
Fixed issue for working with webpack.
