### ISSUE TITLE
[Incomplete] virtual repeate for UIDataGrid

### ISSUE THREAD

**Issue by avrahamcool** [adarshpastakia/aurelia-ui-framework#104]
https://github.com/adarshpastakia/aurelia-ui-framework/blob/15add3446b4241e4ed4c2cb10c0b0032802becad/src/elements/components/ui-datagrid.ts#L175

looks like there is an option to set the virtual flag to `true` by setting the `virtual` attribute on the grid.
but I think the template don't include the code that actually creates the repeat.

here we can see the line that take care of the regular repeat.

https://github.com/adarshpastakia/aurelia-ui-framework/blob/15add3446b4241e4ed4c2cb10c0b0032802becad/src/elements/components/ui-datagrid.ts#L159

**Comment by ronenziv** [comment]
Hi,
we need too virtual for UIDataGrid in version 4

Thanks

**Comment by avrahamcool** [comment]
looks like this should be closed via https://github.com/adarshpastakia/aurelia-ui-framework/commit/df25a451efe27a144262110537078432da0095a7.
@adarshpastakia am I right?

**Comment by ronenziv** [comment]
Hi,
there is a bug, when I using virtual scroll at uidatagrid v4 the sortable is not working

Thanks

**Comment by avrahamcool** [comment]
is it the same as https://github.com/adarshpastakia/aurelia-ui-framework/issues/92?

**Comment by ronenziv** [comment]
No, the problem not relevant to resizeable RTL (this is other bug).
when I using virtual the sortable is not working. when I cancel the virtual the sortable is OK.
