### ISSUE TITLE
Ripple effect

### ISSUE THREAD

**Issue by SuricateCan** [adarshpastakia/aurelia-ui-framework#105]
I would be nice if some of the widgets offered support for ripple effect, like on buttons over material design.

**Comment by avrahamcool** [comment]
@adarshpastakia maybe this can be done with a single custom attribute that can be applied anywhere the user wants?
that way, it doesn't interfere with the user who don't like it (and also will not add any overhead).
and it can be managed in one single place.

**Comment by adarshpastakia** [comment]
use `<ui-button class="ui-effect-ripple">`

*Need to rebuild css*, for now made change to sass file
