### ISSUE TITLE
Dropdown button did not work after refresh data on Datagrid

### ISSUE THREAD

**Issue by longhuynh** [adarshpastakia/aurelia-ui-framework#106]
I have a column in data grid:

`<ui-dg-button  label="Actions" width="5em" dropdown.bind="btnMenu">&nbsp;</ui-dg-button>`

and in the outside:

    <ui-menu ref="btnMenu">
      <ui-menu-section>Actions</ui-menu-section>
      <ui-menu-item glyph="ui-icon-edit">Edit</ui-menu-item>
      <ui-menu-item glyph="ui-icon-trash">Delete</ui-menu-item>
      <ui-menu-section>Options</ui-menu-section>
      <ui-menu-item glyph="ui-icon-cog">Settings</ui-menu-item>
    </ui-menu>

It worked at first time, but when I refresh/sort data. The dropdown button stopped.

**Comment by jblackburn21** [comment]
Removing this line from the detached method on UIButton resolves the issue.

`if (this.dropdown) DOM.removeNode(this.dropdown);`

What is it needed for?
