### ISSUE TITLE
Migrated to other Framework

### ISSUE THREAD

**Issue by hmuhdkamran** [adarshpastakia/aurelia-ui-framework#107]
It is a very elegant UI Framework, but it is available only for Aurelia, how about creating Vue, React or Angular branches.

**Comment by avrahamcool** [comment]
I cant speak on behalf of @adarshpastakia , but I think the library is very dependent on Aurelia.
I don't see an easy way of porting porting it to other frameworks without a massive rewrite.
But this can be a very good thing to do.

similar to:
https://github.com/adarshpastakia/aurelia-ui-framework/issues/98

**Comment by hmuhdkamran** [comment]
I will try to start rewrite it for vue, hope fully it will be as smooth as this one.

**Comment by avrahamcool** [comment]
looking forward to seeing this. it's a very good idea.
