### ISSUE TITLE
Add generic `ui-floating` style to allow dropdown panels

### ISSUE THREAD

**Issue by ronenziv** [adarshpastakia/aurelia-ui-framework#108]
Hi,
We upgrade our project to v4.11beta becuase of the scroll RTL.
Is there implementation to Button with dropdown form ?
In the example of v4 it does not exist but in v3 it does.

Thanks

**Comment by adarshpastakia** [comment]
For now you could try 

```html
<ui-button dropdown.bind="btnForm"></ui-button>
<div class="ui-menu" ref="btnForm"><!-- place form here --></div>
```

need to add a generic `ui-floating` class with tether classes, at the moment its only available with `ui-menu`

**Comment by adarshpastakia** [comment]
Fixing in 4.0.0-Beta.13

```html
<ui-button dropdown.bind="btnPanel" hide-on-click="false"></ui-button>
```
