### ISSUE TITLE
Add checkbox and switch column types

### ISSUE THREAD

**Issue by ronenziv** [adarshpastakia/aurelia-ui-framework#111]
Hi,
we need to use "ui-dg-checkbox" at UIDataGrid like ui-dg-button

how we can use this ?

Thanks

**Comment by avrahamcool** [comment]
this should be enlarged to allow custom template in the column.
a lot of current code can be removed because it's too specific.
if we allow custom template inside a column - we can let the user define whatever he likes.

**Comment by adarshpastakia** [comment]
@avrahamcool yes thats what I want to do, need to find a good way of achieving that

**Comment by ronenziv** [comment]
Hi,
we need to use date, number and so on as custom template in the column.

Thanks

**Comment by adarshpastakia** [comment]
Added `ui-dg-tpl` column to provide template columns

Ex.

```html
<ui-dg-tpl><ui-button click.trigger="viewModel.click()">${record.name}</ui-button></ui-dg-tpl>
<ui-dg-tpl><ui-input value.bind="${record.name}"></ui-input></ui-dg-tpl>
```

Binding properties `record`, `viewModel`

**Comment by ronenziv** [comment]
Hi,
thanks a lot for this feature. it will upgrade our system a lot.

**Comment by ronenziv** [comment]
Hi, 
How can I give title to that column ?

Thanks

**Comment by avrahamcool** [comment]
@ronenziv try that:
```html
<ui-dg-tpl header-title="Your header">YOUR DATA GOES HERE</ui-dg-tpl>
```

the title can also can be bound:
```html
<ui-dg-tpl header-title.bind="someVar">YOUR DATA GOES HERE</ui-dg-tpl>
```

**Comment by ronenziv** [comment]
thanks. it is great !!!
it is worth to update the Documentation : cancel the format option at ui-dg-column

**Comment by ronenziv** [comment]
Hi,
I think there is a problem with ui-switch, ui-checkbox at ui-datagrid:
<ui-dg-tpl header-title="switch"><ui-switcher value.bind="record.isSwitchOn" on-label="on" off-label="off"></ui-switcher></ui-dg-tpl>

I can not switch it. out of the grid <ui-switcher value.bind="mydatasource[0].isSwitchOn" on-label="on" off-label="off"></ui-switcher>
it is OK

input, datapicker is OK.

Thanks
