### ISSUE TITLE
Add SASS variable to control input label alignment

### ISSUE THREAD

**Issue by ronenziv** [adarshpastakia/aurelia-ui-framework#114]
Hi,
it is look like that ui-input-label in V4 not support RTL like in version 3

Thanks

**Comment by avrahamcool** [comment]
are you talking about the labels inside an input group?
looks like it's taking `ltr/rtl` into account - you can see it action in the demo page [here](https://adarshpastakia.github.io/aurelia-ui-framework/#/text)
switch the direction will change the direction - and text of the label will also switch.

the current UI align the text to `flex-end`, I think that what is causing you to think it's not properly aligned.

**Comment by adarshpastakia** [comment]
Add a variable to control input label alignment, default alignment start.

```sass
$input-label-align: start | end;
```

**Comment by adarshpastakia** [comment]
Fixing in 4.0.0-Beta.13
