### ISSUE TITLE
sortable at ui-dg-column-group v4

### ISSUE THREAD

**Issue by ronenziv** [adarshpastakia/aurelia-ui-framework#115]
Hi,
the option of sortby at ui-datagrid -> ui-dg-coulumn-group -> ui-dg-coulumn sortable not work at V4 

Thanks

**Comment by adarshpastakia** [comment]
@ronenziv the column sorting works on any column regardless of group. can you explain what it is thats not working

**Comment by ronenziv** [comment]
Hi,
when I using sortable at ui-dg-column-group -> ui-dg-column I have exception:
cannot read property 'sortBy' of undefined at HeaderCell.get [as sortOrder]...
if I do not use ui-dg-column-group it is OK.
my I miss something ?
Thanks
