### ISSUE TITLE
[Discussion] reverse the default of `user-select` to be selectable

### ISSUE THREAD

**Issue by avrahamcool** [adarshpastakia/aurelia-ui-framework#119]
the current behavior is that everything is unselectable.
you have to apply the `ui-selectable` class to make something selectable.
but it's very counter intuitive, as most real world sites let you select text.
this should be inverted:
the default should be that everything is selectable (just dont apply anythig to the `html` tag),
and we should have a class for `ui-unselectable`.

**Comment by adarshpastakia** [comment]
The reason for it was that this framework was designed for web based applications, however in the case of using with websites I agree so for that scenario we can have a flag in sass whether to apply no select globally or not

**Comment by avrahamcool** [comment]
I created a sass flag
```sass
//default user-select behaviour
$disableUserSelection: true !default;
```

and added a new class `ui-unselectable` that can be applied on any child.
just like the `ui-selectable` that was already available.

```sass
  .ui-selectable {
    @include user-select(text);
  }
  .ui-unselectable {
    @include user-select(none);
  }
```


closed via: https://github.com/adarshpastakia/aurelia-ui-framework/commit/a25035ebd8f88cec2115c6cdaada1bd77e615328
