### ISSUE TITLE
bluebird.min.js:31 Unhandled rejection TypeError: Cannot read property 'attrToRemove' of undefined

### ISSUE THREAD

**Issue by ayaanraj** [adarshpastakia/aurelia-ui-framework#124]
I'm using Aurelia-skeleton-esnext and I have installed plugin as shown below:
```
jspm install npm: aurelia-ui-framework
````
and in main.js
```
import 'bootstrap';

export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .plugin('aurelia-authentication')
    .plugin('aurelia-configuration')
    .plugin('aurelia-ui-framework')
    .developmentLogging();

  aurelia.start().then(() => aurelia.setRoot());
}

```
Just after installation of this plugin in get the error as shown below:

![screenshot from 2018-05-26 13-42-32](https://user-images.githubusercontent.com/29095142/40574143-1894cca0-60eb-11e8-9bf1-b39aa2a27fae.png)

**Comment by avrahamcool** [comment]
you also need to turn on 'aurelia-validation' and 'aurelia-ui-virtualization' features.

**Comment by avrahamcool** [comment]
@ayaanraj can you report back if it helped? so we can close the issue.

**Comment by ayaanraj** [comment]
It has worked, thanks.
