### ISSUE TITLE
ui-button v4 active even disabled.bind=true

### ISSUE THREAD

**Issue by ronenziv** [adarshpastakia/aurelia-ui-framework#125]
Hi,
click.delegate active even if I use disabled.bind=true

Thank

**Comment by adarshpastakia** [comment]
`click.delegate` responds to a click on anything in the container, when not disabled the original click event is cancelled and a custom click event fired from the button, however when its disabled the `pointer-event` is set to none therefore the click is propagated to the parent container.

please use `click.trigger` on the button instead
