### ISSUE TITLE
Got sass compile error

### ISSUE THREAD

**Issue by wind13** [adarshpastakia/aurelia-ui-framework#127]
When I try the aurelia-ui-framework, got the sass error like this:

```
Error: Base-level rules cannot contain the parent-selector-referencing character '&'.
         on line 54 of /path-to-demo/node_modules/aurelia-ui-framework/sass/mixins/_typo.scss, in `selection'
```

I am not sure what is the problem, guess it is because sass version or I miss something?

My SASS version:

> Sass 3.5.5 (Bleeding Edge)

**Comment by avrahamcool** [comment]
what is your project configuration?
I had this problem in one of my projects using require+ESNEXT, when I updated to the latest sass version (I didn't have any problem with earlier version) - but I don't recall the exact versions that work / didn't work.
I currently work on projects with webpack+TS, and I don't have any problem with latest sass.

I think the main difference is that the require + ESNEXT version of the aurelia-cli comes with `gulp-sass`,
and webpack+TS comes with `node-sass`.

**Comment by wind13** [comment]
I am using `System.js` and `TypeScript` and `PostCSS`, but `aurelia-ui-framework` looks like not using `PostCSS` but `sass`. So I install gulp and compass to compile sass, then got the error.

I think you are right, if you using `gulp-sass`, maybe you will meet this problem.

Now, I download the `app.css` manually, and put it in `/css/` folder, it works now. But that may not be the best practice then.

**Comment by adarshpastakia** [comment]
@wind13 try using this gulp script, make sure you have installed `gulp-sass`

```
gulp.task('sass', function(done) {
  return gulp.src('sass/**/*.scss').pipe(sass({
    outputStyle: 'compressed',
    includePaths: ['node_modules/aurelia-ui-framework/sass']
  })).pipe(gulp.dest('./css'));
});
```

**Comment by avrahamcool** [comment]
@adarshpastakia this can be fix in the sass file, so no matter what version the user uses - it'll work.
the issue + resolution is explained here.
https://github.com/sass/sass/issues/1873

there might be a lot of places where it should be fixed. (the error shows only the first occurrence).

**Comment by wind13** [comment]
@adarshpastakia I tried you solution, it works, got a new app.css file. But got an error in the same time:

```
$ gulp sass
...
[14:53:57] 'sass' errored after 412 ms
[14:53:57] RangeError [ERR_OUT_OF_RANGE]: The value of "mode" is out of range. Received 33152
    at Object.fs.fchmod (fs.js:1058:11)
    at Object.fchmod (/path-to-demo/node_modules/graceful-fs/polyfills.js:237:17)
    at mode (/path-to-demo/node_modules/vinyl-fs/lib/file-operations.js:237:10)
    at onStat (/path-to-demo/node_modules/vinyl-fs/lib/file-operations.js:227:14)
    at /path-to-demo/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:185:5)
[1]    19187 segmentation fault  gulp sass
```
