### ISSUE TITLE
Goals for the auf-v4 for exiting the beta stage

### ISSUE THREAD

**Issue by avrahamcool** [adarshpastakia/aurelia-ui-framework#130]
hi @adarshpastakia,

I was wondering what are the goals to accomplish for v4 to exit the beta stage to full release?
there are some important point that should not be missed.

* fixing `auf` to work out of the box with project created via the `cli`.
this is the most important task - because new users will not invest more than a few minutes in a library if it's not working for them immediately and easily.
`no new users = dead project`.

currently there are some problems related to that.
1. the new versions of tempting disallow usage such as `submit.trigger="return false"` -
https://github.com/adarshpastakia/aurelia-ui-framework/issues/129
2. incomplete documentation of how to set-up the framework correctly - leading to problems like
https://github.com/adarshpastakia/aurelia-ui-framework/issues/124
3. incompatible version of `aurelia-ui-virtualization` is causing for an error when loading a project with `auf` even without actually using anything.
I'm pretty sure I've submitted a commit that fixed `package.json` to use the latest  `aurelia-ui-virtualization` - but it got reverted for some reason.

* improving loading size of the framework
1. `auf` is a huge framework - far larger than it should really be.
part of this is because of extra `frameworks` inside that are not really related to `auf`.
the average user will never use the countries, and phone lib included.
2. when the frameworks loads - all of the `components` are automatically being registered globally.
causing a larger up-time and larger memory cost.
users generally don't need to use every component.
we should use the configuration option that is passed to the framework at initialization to register only what the user wants.
we can do this in a non-breaking-changes manner, so that a user who don't specify anything - will load the all framework just like now.
but a more sophisticated user can use this option to determine exactly what he wants to load.

* improving the code base for future contibutors
1. all of the `components` uses the "one-file-component" style, using `inline-view`.
and almost all files have multiple components in them.
this make helping to the project really hard.
it's not intuitive to find the component you are trying to fix - because it's not in it's own file.
and the `inline-view` is probably easier when their is nothing in the view, but using `inline-view` for the grid? it's not helping at all - you don't get`html` intellicence, you have to escape every "$" and a lot of other problems like lack of indentation and so on.
there is not even one positive reason for using `inline-view` in those components.
it's a large frameworks - keeping it organized with multiple files is better then throwing multiple components in the same file (in my opinion).
2. there is a lot of repeated code in the code base - that is making it very hard to fix bugs and know that you fixed it everywhere. (for instance: all of the inputs have a lot of functionality in common - but that is not written in the parent class but instead [sometimes] copied in each component].

I know its a long list of things that should be done.
I want to contribute more in the near future, and I'll probably also assign some of my team members to help me with that.
but I need to know that you are on board with that vision.
we will need to have rapid and frequent publishing cycles.
will you consider sharing the writes to npm publish?
will you have time in the near future to help with `auf`?

**Comment by avrahamcool** [comment]
@adarshpastakia your thought will be greatly appreciated.

**Comment by firstfocus** [comment]
Hi @avrahamcool @adarshpastakia just wondering, is there any progress on a new v4 release? I would be interested in helping if the project is not dead which does seem to be the case unfortunately.

**Comment by avrahamcool** [comment]
Ill wait a little more for adrash response, but currently it looks like im the only active member here.

the changes I want to do are very big.. 
and im waiting for the right apportunity at work to start the work on this. 
I also intend to put some coworkers from my team on this. 

it will be very beneficial to have more help. 

right now, the project dont attract a lot of attention, but I hope we can improve it and bring more of the aurelia community.

**Comment by firstfocus** [comment]
Thanks for the fast reply. We are using v3 but I really want to update. Still seems to be the most feature complete framework and I'm not a fan of aurelia-ux yet(!) :-) I will continue to test V4 and if I come across any issues that are currently open I will see what I can do to fix them.
