### ISSUE TITLE
Remove bootstrapper from dependencies list

### ISSUE THREAD

**Issue by bigopon** [adarshpastakia/aurelia-ui-framework#145]
@adarshpastakia @avrahamcool I see that `aurelia-bootstrapper` is specified as a dependencies, but it seems unnecessary for a library. This could cause issue to not smart enough bundler, ie codesandbox. Also it may even cause duplicate dependencies issues to webpack. I think it'd be better if aurelia-bootstrapper was not listed as a dependencies.

Also I notice few other possible improvement:
aurelia-binding can be specifically listed at 2.x, to ensure compat with core libs
aurelia-templating can be specified at 1.8.1^ (best is 1.10.1+) so `PLATFORM.moduleName` can be replaced by direct class references.

I can also help with all in one build (UMD) for better compatibility with `aurelia-script`.

**Comment by avrahamcool** [comment]
I'll be happy to make those improvements.

what need to be done for the UMD build?

**Comment by bigopon** [comment]
The immediately obvious to me is using newer features of templating. For example, remove all `PLATFORM.moduleName` and use direct class reference instead, as I can see that all views are already inline, which is nice

I think after that we can start looking into creating a build configuration for the whole build, particularly like official plugins.

**Comment by avrahamcool** [comment]
@adarshpastakia you are the only one that can publish to NPM.
what do you think about this?
