### ISSUE TITLE
es2015 dist folder output? 

### ISSUE THREAD

**Issue by MeirionHughes** [adarshpastakia/aurelia-ui-framework#15]
The new Aurelia webpack plugin is able to pick dist files from a `/dist/es2015` folder during build. The benefit is that any export that isn't directly used by the built app can be removed (tree shaking). 

from the looks of the dist at the moment, its require module format?

Might be worth having a `/dist/es2015` folder in the publish package so applications can take advantage of tree shaking (see https://github.com/jods4/aurelia-webpack-build/tree/master/demos/04-Small_ES6_build). Its pretty much exactly the same output as you have now, but just targetting es2015 and in the `/dist/es2015` folder.

**Comment by adarshpastakia** [comment]
@MeirionHughes 
Added other `dist` folders, however since I'm using `/amd` have not been able to test the others
