### ISSUE TITLE
use PLATFORM.moduleName() for module ids 

### ISSUE THREAD

**Issue by MeirionHughes** [adarshpastakia/aurelia-ui-framework#16]
Aurelia Webpack plugin requires that you use the PLATFORM.moduleName() method to wrap your moduleIds. See this discussion: https://github.com/aurelia/pal/issues/17

basically anywhere in source code where you have `moduleId: "./foo/bar"` needs to be changed to `moduleId: PLATFORM.moduleName("./foo/bar")`.

**Comment by adarshpastakia** [comment]
Updated in 3.1.0
