### ISSUE TITLE
Why all of the empty callbacks?

### ISSUE THREAD

**Issue by AshleyGrant** [adarshpastakia/aurelia-ui-framework#17]
I was looking at the source code and I'm seeing stuff like:

```
  // aurelia hooks
  canActivate(model) { return true; }
  activate(model) { return true; }
  bind(bindingContext) { }
  attached() { }
  detached() { }
  unbind() { }
  deactivate() { }
  // end aurelia hooks
```

repeatedly. Why are all of these empty callbacks being added? Aurelia doesn't require these callback methods be added to a viewmodel. If the callback isn't implemented, Aurelia won't call it.

**Comment by adarshpastakia** [comment]
@AshleyGrant i added a snippet for view-model which has these blank hooks, maybe i should comment them by default and uncomment the ones needed for each view-model.

**Comment by AshleyGrant** [comment]
I just want to say that what you've built here is really awesome! I tweeted about it this morning and the Aurelia Framework twitter retweeted it here: https://twitter.com/ashleymgrant/status/847444163830337536

Thank you for building something great!

**Comment by adarshpastakia** [comment]
@AshleyGrant Thanks for the tweet 😃
