### ISSUE TITLE
Datagrid enhancements

### ISSUE THREAD

**Issue by ratones** [adarshpastakia/aurelia-ui-framework#18]
Any chance of adding new  features to grid?
I'm thinking of  server data, grouping, nested grids...
Right now  i'm using some other libraries in  my  applications, but Aurelia looks very promissing and  this ui  framework makes it even more  appealing. Fetching data  from server would be a great  enhancement...

**Comment by adarshpastakia** [comment]
@ratones yes hopefully i will get to it soon, for the moment I'm trying finish with the wikis and few issues i keep finding.

On my list
1. Row expander with inner grid or plain content, i too have a need for this in one of my projects
2. Option for server-data, basic options i was thinking of adding
```
{
url,
dataProperty,
pageProperty,
totalProperty,
}
```

Grouping? do you mean column groups?

**Comment by adarshpastakia** [comment]
#19 Server data
#20 Row expander
