### ISSUE TITLE
Datagrid row expander 

### ISSUE THREAD

**Issue by adarshpastakia** [adarshpastakia/aurelia-ui-framework#20]
Possible views 
1. Composed view
2. Drilldown type inner grid

**Comment by ratones** [comment]
I would go with composed view.
In my opinion the nested grid should be as much as possible decoupled from parent. 
The parent should pass some parameters, but then the child should take over.

Thanks.

**Comment by adarshpastakia** [comment]
@ratones due a requirement in my project, i updated the data grid to display subtable data on expand. later on will try to improve on it to have custom views
