### ISSUE TITLE
Couldn't run on clean project created using Aurelia CLI

### ISSUE THREAD

**Issue by ma3yta** [adarshpastakia/aurelia-ui-framework#22]
Repo is available by https://github.com/nowinfinity/nowinfinity.abr.site
![Error](https://i.gyazo.com/e4c4e297ab7ec1c20169d8efed538063.png)

**Comment by adarshpastakia** [comment]
@Ma3yTa It seems to be missing typescript definition in aurelia.json

[Setup](https://github.com/adarshpastakia/aurelia-ui-framework/wiki/Setup)

**Comment by adarshpastakia** [comment]
@Ma3yTa  I'm closing this issue for now, let me know if you still have an issue with it.
