### ISSUE TITLE
Questions, future development

### ISSUE THREAD

**Issue by firstfocus** [adarshpastakia/aurelia-ui-framework#226]
Hi @adarshpastakia hope you are well. I have been attempting to convert an old V3 app to V5 and have some questions but am wondering if it is still worthwhile. Are you still maintaining this and willing to answer questions? If so, one question I have is what the best approach would be to close a modal/dialog from within the loaded view model. In V3 I extended the dialog and this worked. Any hint would be appreciated :) If not that would be a shame but understandable. Cheers!

**Comment by adarshpastakia** [comment]
Hi @firstfocus , apologies for a late response.
for the dialog issue you could try `<ui-dialog label="My Dialog" view-model.bind="vmDialog">` and then `vmDialog.close()`

As for the library itself, the present circumstances at work with the move from aurelia to react is making it difficult for me to keep it going, i have been wanting to checkout the latest aurelia and improving the ui-framework but unfortunately have been spending all of my time on react. will certainly come back to this one of these days, but until then will try my best to help out when possible

Be safe, cheers!

**Comment by firstfocus** [comment]
No apology necessary, thanks for the reaction and help. I figured it out and got it to work bij calling: vmDialog.activeWin.close();  Would be great if you could still help with updates :) Take care!
