### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by zodraz** [adarshpastakia/aurelia-ui-framework#27]
Hi I cannot compile the code. I find this error relating to the module aurelia-ui-framework, which appears not to properly find on the jspm_packages\github\adarshpastakia.

main.ts(3,28): error TS2307: Cannot find module 'aurelia-ui-framework'.
src\app.ts(3,34): error TS2307: Cannot find module 'aurelia-ui-framework'.
src\home\buttons.ts(2,51): error TS2307: Cannot find module 'aurelia-ui-framework'.
src\home\datagrid.ts(1,22): error TS2307: Cannot find module 'aurelia-ui-framework'.
src\home\dialogs.ts(2,50): error TS2307: Cannot find module 'aurelia-ui-framework'.
src\home\form.ts(4,40): error TS2307: Cannot find module 'aurelia-ui-framework'.
src\home\tree.ts(1,36): error TS2307: Cannot find module 'aurelia-ui-framework'.
src\login\view.ts(2,34): error TS2307: Cannot find module 'aurelia-ui-framework'.
[16:31:50] TypeScript: 8 semantic errors
[16:31:50] TypeScript: emit succeeded (with errors)
[16:31:50] Finished 'scripts:compile' after 6.42 s

Also when trying to fix the error (which shouldn't be the case) moving from jspm_packages\github and putting the proper typing on the typings folder, I get the error on main.ts that  {UIValidation} from "aurelia-ui-framework"; is not exported, which I can confirm looking at the typings, there's no so UiValidation export inside aurelia-ui-framework.d.ts.

Also the package downloaded and used for npm is aurelia-ui-framework@1.2.2.

Thanks so much

**Comment by adarshpastakia** [comment]
There was an issue with the skeleton setup, i have updated the fix. Please update the main.ts file and also install the package as `jspm install aurelia-ui-framework`

**Comment by zodraz** [comment]
Still the same problem (and another error), but I see you changed the UIValidation.

[11:28:20] Starting 'scripts:compile'...
main.ts(3,36): error TS2307: Cannot find module 'aurelia-ui-framework'.
src\app.ts(3,34): error TS2307: Cannot find module 'aurelia-ui-framework'.
src\home\buttons.ts(2,51): error TS2307: Cannot find module 'aurelia-ui-framework'.
src\home\datagrid.ts(1,22): error TS2307: Cannot find module 'aurelia-ui-framework'.
src\home\dialogs.ts(2,50): error TS2307: Cannot find module 'aurelia-ui-framework'.
src\home\form.ts(4,40): error TS2307: Cannot find module 'aurelia-ui-framework'.
src\home\tree.ts(1,36): error TS2307: Cannot find module 'aurelia-ui-framework'.
src\login\view.ts(2,34): error TS2307: Cannot find module 'aurelia-ui-framework'.
typings\aurelia\aurelia-framework.d.ts(209,3): error TS2308: Module 'aurelia-binding' has already exported a member named 'Callable'. Consider explicitly re-exporting to resolve the ambiguity.

**Comment by adarshpastakia** [comment]
@zodraz I have updated the skeleton project with the latest typings file, have also tested a clean setup from the latest skeleton archive and there are no issues in compiling the scripts.

do let me know if you are still facing an issue.

**Comment by DINHDUY** [comment]
Found this error in the skeleton beta 1.2.5. Too many errors,last one:
ERROR in ./src/app.ts
(2,43): error TS2307: Cannot find module 'aurelia-router'.

**Comment by adarshpastakia** [comment]
@DINHDUY have you run the init script, looks like you are missing the aurelia dependencies
