### ISSUE TITLE
missing http.js and data.js

### ISSUE THREAD

**Issue by stephenhuey** [adarshpastakia/aurelia-ui-framework#29]
Getting a 404 when trying to view your **HTTP Client** info:

https://adarshpastakia.github.io/aurelia-ui-framework/src/api/http.js

Tried to reach it from here:

https://adarshpastakia.github.io/aurelia-ui-framework/#/

The same goes for `data.js` and `event.js` and I noticed this link is also not working:  

https://adarshpastakia.github.io/aurelia-ui-framework/#/api/http/

**Comment by stephenhuey** [comment]
For the record, I did at least find this on the wiki:  

https://github.com/adarshpastakia/aurelia-ui-framework/wiki/UIHttpService

**Comment by ratones** [comment]
AFAIK docs and examples are still work in progress. 
At the moment new features are added to the framework.
