### ISSUE TITLE
Is Datagrid Editable?

### ISSUE THREAD

**Issue by gregoryagu** [adarshpastakia/aurelia-ui-framework#34]
First a comment: I have not seen this UI framework before, but have done many Aurelia project.  I really like aurelia-ui-framework.

Question: Is the data grid editable?  I have a project I am just starting and I was going to use Syncfusion datagrid.  But I would rather use the aurelia-UI-framework and use the grid as well as the other widgets.

Thank you for you work on this project.

**Comment by adarshpastakia** [comment]
@gregoryagu at the moment no, will be working on it once i figure out a good way of dealing with it

**Comment by gregoryagu** [comment]
The usual way is to have an observerable collection.  When an item is added, it fires an event and the item is added.  An also if an item is changed, it fires an event so the UI can be updated.

Neither Syncfusion or Kendo support this at this time, so I end up using hacks to keep the UI in sync with the data. So if aurelia-ui-framework did, that would be really great.
