### ISSUE TITLE
Make ui-option-group stack contents vertically

### ISSUE THREAD

**Issue by emcga** [adarshpastakia/aurelia-ui-framework#36]
Is there a way to make the contents of a ui-option-group stack vertically? I have one filled with checkboxes and would like to have them stack on top of one another. If this is not possible is there another way I can achieve this using the framework?

@adarshpastakia thanks for creating a business oriented ui framework! This was exactly what I was looking for.

Thanks,
Eric

**Comment by adarshpastakia** [comment]
@emcga i have updated the sass and styles to have vertical option groups, although its not yet updated in a release, or you can add the following to your css and use `<ui-option-group class="ui-vertical">`

```
.ui-input-group.ui-vertical .ui-option-group {
  flex-direction: column;
  .ui-option {
    margin: 0.2em 0;
    flex: 0 0 auto;
  }
}
```

i will try to include this as a singular attribute for the custom element itself.

Glad you are finding this framework useful, although there are still a few issues to be ironed out, shall keep you updated

**Comment by emcga** [comment]
That worked perfectly! Thank you.
