### ISSUE TITLE
please provide the theme for bootstrap too

### ISSUE THREAD

**Issue by HamedFathi** [adarshpastakia/aurelia-ui-framework#36]
Can you provide theme of Aurelia ui framework for bootstrap too ?
like [https://bootswatch.com](https://bootswatch.com)

Sometimes we use Aurelia ui framework controls beside some bootstrap plug-ins and controls so we need to have same theme for whole the site and controls.

Is it possible ?

**Comment by adarshpastakia** [comment]
@HamedFathi for the moment wont be possible to look into that, am currently working on adding features for the datagrid and a data source component
however did you mean bootstrap theme for the ui framework or ui framework theme for bootstrap?

**Comment by HamedFathi** [comment]
@adarshpastakia ,

of course **ui framework theme for bootstrap**

I think for having unified theme we need that.

anyway thanks for your efforts
