### ISSUE TITLE
Demo doesn't load in Firefox and loads very slow in Edge

### ISSUE THREAD

**Issue by kellyethridge** [adarshpastakia/aurelia-ui-framework#37]
Hello,
Nice UI you have here :+1: . Unfortunately the demo page fails to load in Firefox. I get the following error:

`Unhandled promise rejection TypeError: this.strategy is null
Stack trace:
k</a.prototype._observeCollection@http://adarshpastakia.github.io/aurelia-ui-framework/dist/demo.js:1:25976
k</a.prototype.itemsChanged@http://adarshpastakia.github.io/aurelia-ui-framework/dist/demo.js:1:24964
k</a.prototype.bind@http://adarshpastakia.github.io/aurelia-ui-framework/dist/demo.js:1:24442
La</a.prototype.bind@http://adarshpastakia.github.io/aurelia-ui-framework/dist/demo.js:26:16873
ua</a.prototype.bind@http://adarshpastakia.github.io/aurelia-ui-framework/dist/demo.js:25:27608
La</a.prototype.bind@http://adarshpastakia.github.io/aurelia-ui-framework/dist/demo.js:26:16559
ua</a.prototype.bind@http://adarshpastakia.github.io/aurelia-ui-framework/dist/demo.js:25:27608
ua</a.prototype.bind@http://adarshpastakia.github.io/aurelia-ui-framework/dist/demo.js:25:27667
ua</a.prototype.bind@http://adarshpastakia.github.io/aurelia-ui-framework/dist/demo.js:25:27667
ua</a.prototype.bind@http://adarshpastakia.github.io/aurelia-ui-framework/dist/demo.js:25:27667
ua</a.prototype.bind@http://adarshpastakia.github.io/aurelia-ui-framework/dist/demo.js:25:27667
ua</a.prototype.bind@http://adarshpastakia.github.io/aurelia-ui-framework/dist/demo.js:25:27667
La</a.prototype.bind@http://adarshpastakia.github.io/aurelia-ui-framework/dist/demo.js:26:16559
La</a.prototype.automate@http://adarshpastakia.github.io/aurelia-ui-framework/dist/demo.js:26:15832
l</a.prototype.swap/<@http://adarshpastakia.github.io/aurelia-ui-framework/dist/demo.js:7:28242
C/</g@http://adarshpastakia.github.io/aurelia-ui-framework/dist/demo.js:32:12382
C/<@http://adarshpastakia.github.io/aurelia-ui-framework/dist/demo.js:32:12491
l@http://adarshpastakia.github.io/aurelia-ui-framework/dist/demo.js:32:9272`

I hope it's something simple

**Comment by adarshpastakia** [comment]
I have deployed a new build, the issue has been resolved on firefox. 
As for MSEdge i havent yet tested it on a windows machine as yet, am hoping to iron out a few pending issues and enhancements before that
