### ISSUE TITLE
Datagrid Layout Update

### ISSUE THREAD

**Issue by adarshpastakia** [adarshpastakia/aurelia-ui-framework#37]
**Major Update**
- Changed datagrid layout from table to flex box divs
- Locking columns using css transform

*Issues*
- Stuttered scrolling in Safari
- Untested in browsers on Windows

*Tested*
- Chrome
- Firefox
- Opera

#20 
#24

**Comment by adarshpastakia** [comment]
Tested on Windows
- Firefox
- Edge

**Comment by avrahamcool** [comment]
datagrid loses horizontal scroll in RTL.
