### ISSUE TITLE
Installation missing init.bat

### ISSUE THREAD

**Issue by Lulik** [adarshpastakia/aurelia-ui-framework#39]
Hi
i downloaded the skeleton and there is a missing init.bat
anyway i followed the instructions on the init.sh.
it looks like everything is ok but when running gulp watch the site doesn't appear.
any idea?

**Comment by adarshpastakia** [comment]
`gulp watch` will compile ts and scss files only when its notified of a change in the files. 
to browse the site run `gulp serve` and then open `localhost:9000` in your browser.

**Comment by Lulik** [comment]
Thanks!

**Comment by Lulik** [comment]
now running the application give this error (in chrome):
Failed to load resource: the server responded with a status of 404 (Not Found)
:9000/#/home:1 Fetch API cannot load https://api.hmcmosaic.com/api./src/home/example.md. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9000' is therefore not allowed access. The response had HTTP status code 404. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
any idea? thanks

**Comment by adarshpastakia** [comment]
There is a mistake in the main.js, the baseUrl should be './'

**Comment by Lulik** [comment]
Hi,
i am trying to use the data grid, is there any way to get the data from url? API?

Thanks

Eli

**Comment by adarshpastakia** [comment]
@Lulik for the moment the datagrid needs to have a bound data-list, so for now the data will have to fetched manually using the UIHttpService, so in your view-model activate/canActivate method load the data

```javascript
@inject(UIHttpService)
export class vm {
  constructor(httpClient) {
    this.httpClient = httpClient;
  }
  canActivate() {
    return this.httpClient.get(url)
      .then(resp=>this.dgData = resp);
  }
}
```

```html
<ui-datagrid data-list.bind='dgData'>
  <!-- datagrid columns -->
</ui-datagrid>
```

**Comment by adarshpastakia** [comment]
Added init.bat
