### ISSUE TITLE
Add "registry": "npm" to package.json

### ISSUE THREAD

**Issue by aluanhaddad** [adarshpastakia/aurelia-ui-framework#40]
Greetings! Thanks for making this awesome library.

Currently, this package can be installed via jspm without a prefix
```bash
$ jspm install aurelia-ui-framework
```
Unfortunately, no dependencies are installed, because, as the output from jspm indicates, there is no registry property set in the `package.json`.

This can be fixed on a per install basis by using an override
```bash
$ jspm install aurelia-ui-framework -o "{registry: 'npm'}"
```
but requires extra configuration maintenance and more advanced knowledge of jspm.

Another alternative is
```bash
$ jspm install npm:aurelia-ui-framework
```
but that defeats the purpose of the entry that was created in the jspm registry for this package and does not match the behavior of other aurelia libraries.

To remedy this, I propose adding

```json
  "registry": "npm"
```
to `package.json`.

Thank you.

**Comment by adarshpastakia** [comment]
@aluanhaddad thanks for the update

**Comment by aluanhaddad** [comment]
My pleasure, thank you.
