### ISSUE TITLE
Menubar inside an Appheader

### ISSUE THREAD

**Issue by alexisargyris** [adarshpastakia/aurelia-ui-framework#44]
Hi,

I am trying to position a `ui-menubar` next to a `ui-app-title` inside a `ui-app-header`, i.e. something like this:

```
    <ui-app-header>
      <ui-app-title>
        <div style="display: inline-block">app title</div>
        <ui-menubar style="display: inline-flex">
          <ui-menu-item
            repeat.for="option of menuOptions">
            ${option.label}
          </ui-menu-item>
        </ui-menubar>
      </ui-app-title>
    </ui-app-header>
```
The menu bar is displayed briefly and then it gets replaced by a small button which, when clicked, displays the menu options. This looks like an overflow mechanism in case the browser window gets too small to contain the menu bar, but it seems to get activated regardless of the window's size.

Am I missing something?

**Comment by adarshpastakia** [comment]
@alexisargyris i just tried it, looks like the menubar needs to have `position: relative` the offsetLeft of the last child is being calculated on the header and thats causing it to go into overflow.

```html
<ui-app-header>
  <ui-app-title>app title</ui-app-title>
  <ui-menubar style="position: relative">
    <ui-menu-item repeat.for="option of menuOptions">
      ${option.label}
    </ui-menu-item>
  </ui-menubar>
</ui-app-header>
```

**Comment by alexisargyris** [comment]
Great! Thanks a lot
