### ISSUE TITLE
ui-datagrid height issue when inside of ui-panel

### ISSUE THREAD

**Issue by emcga** [adarshpastakia/aurelia-ui-framework#45]
@adarshpastakia When adding a ui-datagrid to a ui-panel the data-grid is not shown. If I inspect the ui-body element of the ui-panel and give it a static height, then I can start to see the grid. It seems that the grid is rendered but the height of the panel is not growing to accommodate the ui-datagrid. FYI the ui-datagrid displays fine when inside of the ui-content element. Thanks for your help.

```html
<template>
  <ui-content>
    <ui-panel>
      <ui-header secondary collapse="false">Contacts</ui-header>
      <ui-body>
        <ui-datagrid data-list.bind="data" summary-row="true" default-sort="FName">
          <ui-data-column locked center width="50" data-id="id">ID</ui-data-column>
          <ui-data-column locked resizeable summary="Total" data-id="FName">Name</ui-data-column>
        </ui-datagrid>
      </ui-body>
    </ui-panel>
  </ui-content>
</template>
```

**Comment by emcga** [comment]
So I downloaded the framework code and added a line under the attached function in ui-datagrid.ts. I'm not sure if this can be considered a permanent fix or a hack. If you would like to incorporate it in the framework code, please feel free to do so. It basically gets the height of the base table and sets the ui-datagrid to that height. 

```javascript
    (<HTMLElement>this.element).style.height = String(this.__table.clientHeight) + "px";
```

**Comment by adarshpastakia** [comment]
@emcga i had made the data grid such that it would take the dimensions of its parent container since the data grid wrapper has scrolling. however in the case of using it in the panel body instead of fixing the table height you could use the below example, i will add the fix in the next update

```css
.ui-datagrid.ui-auto-height > .ui-datagrid-wrapper {
  position: static;
}
```

```html
<ui-panel>
	<ui-header collapse="true" primary>My Panel</ui-header>
	<ui-body>
		<ui-content scroll>
			<ui-datagrid class="ui-auto-height">
				...
			</ui-datagrid>
		</ui-content>
	</ui-body>
</ui-panel>
```

**Comment by emcga** [comment]
Thank you. That is exactly what I was looking for!

**Comment by adarshpastakia** [comment]
Added `auto-height` attribute to UIDataGrid element
