### ISSUE TITLE
could UIDialogService.show() return a promise containing an instance of the dialogs vm?

### ISSUE THREAD

**Issue by emcga** [adarshpastakia/aurelia-ui-framework#46]
@adarshpastakia I am trying to find a way to access the view model of a newly created dialog. I have properties that I would like to access after the dialog is created. Since I have multiple dialogs open at once, each one generates its own unique id upon creation. I need to have access to the ids in order to listen for events from each unique dialog. 

If this isn't the correct approach, do you recommend a possible solution? 

Thanks for your time.

**Comment by emcga** [comment]
Also, I tried to set the id using so I could avoid accessing the view model
```javascript
UIDialogService.show(ViewModel, {id:"1234"})
```

but the id was not set. Am I missing something here??

**Comment by adarshpastakia** [comment]
@emcga Which view-model are you trying to access? I'm not sure what exactly you are trying to do but you could try broadcasting an event from the dialog's view-model

```js
export class MyDialog {
  id;
  bind(model) {
   this.id = model.id;
 }
 publishEvent() {
  UIEvent.publish('DialogEvent', this.id);
 }
}
```

```js
export class MyView {
 openDialog() {
  UIDialogService.show(MyDialog, {id:1});
 }
 attached() {
  UIEvent.subscribe('DialogEvent', id=>{});
 }
}

**Comment by emcga** [comment]
@adarshpastakia I was trying to access the view model instances from the open dialogs, but I actually really like your solution. I've changed my code to use the UIEvent class. This will work great!

Thank you.
