### ISSUE TITLE
[Feature Request] support custom html for tabs title

### ISSUE THREAD

**Issue by avrahamcool** [adarshpastakia/aurelia-ui-framework#46]
The current implementation of the tabs is:

```
<ui-tab id.bind="tab.id" label.bind="tab.label">
    <compose view-model.bind="tab.viewModel"></compose>
</ui-tab>
```
the label of the tab is bounded to a string, and the content (slot) of the tab is HTML (in this example, it's a `compose` tag).

it will be helpful to switch that.
the compose content can be bounded, and the title can go in the slot - that way you have much more freedom over the content of the title. (you can have custom bounded HTML as the title), while maintaining the same freedom that you already have for the content of the tab, because you can write anything you want using the compose tag.

also, the tab `id` can be generated by the framework (using the index of the tab) - and then we can also support API function like `tabs.ChangeSelection(5)`

```
<ui-tab compose.bind="{view: '...', viewModel: '...', model: '...'}">
    <span>the title is HTML</span>
    <ui-glyph if.bind="showGlyph" glyph="glyph-alert-notif" class="ui-anim-color"></ui-glyph>
</ui-tab>
```

I created a project with an implementation of this vision of tabs.
https://github.com/avrahamcool/auf-tabs-showcase
this is a simple and naive implementation that lacks styling, event's etc... I only showcase the custom title.

**Comment by adarshpastakia** [comment]
@avrahamcool it worth exploring however if we switch the default slot from content to label then we are restricting the tab content to be a compose element at all times.
instead we could add a named slot element for the tab title `ui-tab-title`, so one could use the simple label if needed else provide `ui-tab-title` in the tab itself.

```html
<ui-tab>
  <ui-tab-title>
    <span>the title is HTML</span>
    <ui-glyph if.bind="showGlyph" glyph="glyph-alert-notif" class="ui-anim-color"></ui-glyph>
  </ui-tab-title>
  
  <compose view-model=""></compose>
</ui-tab>
```

**Comment by avrahamcool** [comment]
The compose tag is not a real restriction, because you can do whatever you want in it.
But you are right, your solution with the named slots is perfect.

Can you consider an implementation of it to your framework? I will try to create a PR for this if you don't have the time.
(it will be my first PR, so hopefully I wont screw up anything)

**Comment by avrahamcool** [comment]
done in V4
