### ISSUE TITLE
UIDataGrid not updating when data model changes

### ISSUE THREAD

**Issue by emcga** [adarshpastakia/aurelia-ui-framework#47]
@adarshpastakia I noticed that UIDataGrid does not update its table contents when the data model changes. I made a few alterations to the UIDataGrid class to update the table when dataList changes. Here are my changes...

```javascript
//First, import the binding engine
import {BindingEngine} from 'aurelia-framework';


//Second, add this private property
private __dataListChangeSubscriber;

//Third, add these lines to the bind() method
    this. __dataListChangeSubscriber = this.bindingEngine.collectionObserver(this.dataList).subscribe(e=>{
      this.dataListChanged(this.dataList);
    });

//Finally, add this detached method
  detached(){
    this.__dataListChangeSubscriber.dispose();
  }

``` 

I verified that when added to the UIDataGrid class, the above code will update the table when items are added or removed from dataList.

**Comment by adarshpastakia** [comment]
@emcga Thanks for the update, i was expecting the binding to take care of observing the array. i have add your fix for this, will release the update as soon as i can. 

unfortunately running jspm update to the latest aurelia release has broken most of the custom elements.

**Comment by emcga** [comment]
@adarshpastakia No problem, glad I could help. Also, thanks for letting me know about the latest Aurelia release. I will definitely not update until the issues are resolved. Do you know what's breaking the custom elements?
