### ISSUE TITLE
adarshpastakia/aurelia-ui-framework@2.0.6.js 404 (Not Found) error when updating to 2.0.6

### ISSUE THREAD

**Issue by emcga** [adarshpastakia/aurelia-ui-framework#49]
@adarshpastakia When I updated the framework this morning, I received this error message. 

adarshpastakia/aurelia-ui-framework@2.0.6.js 404 (Not Found)

**Comment by emcga** [comment]
Everything is working great now! Thanks.

**Comment by adarshpastakia** [comment]
@emcga Apologies, i released the wrong branch earlier
