### ISSUE TITLE
UIModel discardChanges not discarding fresh model

### ISSUE THREAD

**Issue by avrahamcool** [adarshpastakia/aurelia-ui-framework#49]
calling `discardChanges()` on a model instance that inherits from `UIModel` is not doing anything if you didn't call `saveChanges()` or `isDirty()` at least once before that.

modifying a freshly initialized model, and then discarding the changes should be a valid scenario.

**Comment by avrahamcool** [comment]
I'm closing this issue because calling `saveChanges()` on the parent class in the parent constructor does not help (because the child fields are not initialized at this point).
the only thing we can write in the parent class that can affect the child is using something like `setTimeout` to run `saveChanges()` after the child constructor has finished running.
but it's very ugly.

I prefer simply calling `saveChanges()` in the child constructor - so I can discard any changes immediately.

can you think of a better way (that can be implemented on the parent) that will make the same effect?

**Comment by avrahamcool** [comment]
PR #51 
calling `this.init()` in the child constructor will call `saveChanges()` so you can `discardChanges()` on the model as expected.

**Comment by adarshpastakia** [comment]
@avrahamcool sorry for the late response, I'm in the middle of changing jobs and moving back home. I will try and get to updating the pr soon, the trouble is I been struggling with data model and data store concepts, been trying to work on a local or remote data store coupled with a data model.

**Comment by avrahamcool** [comment]
I want to update the demo section of the app to reflect those changes, and add documentation.
but the code I have (I cloned the repo) does not include the Tester that we can see [here](https://adarshpastakia.github.io/aurelia-ui-framework/#/api/data).
The demo app run a different version?
