### ISSUE TITLE
DataGrid column names are not visible

### ISSUE THREAD

**Issue by emcga** [adarshpastakia/aurelia-ui-framework#50]
@adarshpastakia The data grid columns are not rendering their name. Everything else seems to be working fine though.

**Comment by adarshpastakia** [comment]
@emcga unfortunately i can't publish a quick fix since i seem to have broken the validation, I'm trying to update it to use the latest aurelia validation and validatejs.

However for the moment, you can add the following to ui-datagrid.js, under the class UIDataColumn

```js
UIDataColumn.prototype.attached = function () {
this.__title = this.element.textContent || this.element.innerText;
}
```

**Comment by emcga** [comment]
@adarshpastakia Thank you, I added your code and it fixed the issue. I do appreciate your efforts and I enjoy working with your framework. If there's anything I can do to help, please let me know.

**Comment by emcga** [comment]
Sorry, I did not mean to close this. I know you're still working on it.
