### ISSUE TITLE
aurelia-validation not changing the style of form elements

### ISSUE THREAD

**Issue by emcga** [adarshpastakia/aurelia-ui-framework#51]
@adarshpastakia When validating form data using aurelia-validation the style of the form elements do not change when a validation error occurs. I remember you saying the validation system was having issues; Is this the issue you were talking about?

**Comment by adarshpastakia** [comment]
@emcga im in the process of updating it to the new aurelia validation, however that might cause a bit of an issue in updating the existing validation. 

as for the version you are using it should work ok if you have the following in your `main.ts`

```js
.plugin('aurelia-validation', function (config) {
           config.useViewStrategy(new UIValidationStrategy());
       })```

**Comment by emcga** [comment]
Great! That solves the issue. Thank you.
