### ISSUE TITLE
Migrate to WebPack from JSPM

### ISSUE THREAD

**Issue by adarshpastakia** [adarshpastakia/aurelia-ui-framework#52]
1. Have parallel support for JSPM and WebPack or completely ditch JSPM?
2. Make a WebPack upgrade script to move existing apps from JSPM to WebPack

**Comment by emcga** [comment]
@adarshpastakia It would still be nice to be able to use JSPM if possible.

**Comment by adarshpastakia** [comment]
@emcga Ya i haven't decided on it, I'm still trying to understand web pack, will create a separate init script for web pack. The framework is already available on npm as well jspm via github. 
i have tried to get the skeleton to work with web pack, been reading about improved performances on web pack when compared to jspm.

**Comment by emcga** [comment]
@adarshpastakia gotcha, well if web pack improves performance than that's a plus. As of right now I haven't messed with web pack much, but from what I've read it's just a module loader, not a package manager. I kinda like the package management feature of JSPM. I will do more research tonight. Also, I might be opening up an issue regarding loading data into a ui-combo while inside of a ui-dialog. I just can't seem to get it working.

**Comment by adarshpastakia** [comment]
@emcga  web pack uses npm as the package manager in place of jspm

**Comment by emcga** [comment]
@adarshpastakia ok gotcha, that actually seems like it may simplify things then. Using just one package manager seems appealing. Will definitely research it later. Thank you!

**Comment by adarshpastakia** [comment]
Dropping this in favour of aurala-cli.
