### ISSUE TITLE
ui-combo shows "undefined" options when inside of UIDialog

### ISSUE THREAD

**Issue by emcga** [adarshpastakia/aurelia-ui-framework#53]
@adarshpastakia I cannot seem to get the ui-combo to correctly load options when inside of a UIDialog view. The list displays the correct number of elements in the array, but the display text for each element is "undefined". I made sure I set the correct display-member, and I have successfully used ui-combos throughout the rest of my project without an issue.

**Comment by adarshpastakia** [comment]
@emcga does list object have the display-property you passed to the combo

`<ui-combo display-property="name" options.bind="list"></ui-combo>`

`list = [{id:1,name:'ABC'}]`

**Comment by emcga** [comment]
@adarshpastakia Oh, I was using display-member, not display-property! Changing that fixed it. That's strange though because I have another ui-combo that is using display-member and it's working fine. It's loading the same type of data too.

**Comment by adarshpastakia** [comment]
@emcga the default value and display property are `id` and `name` so if the list item object has a property `name` it will use that by default

```js
    /**
	 * @property    value-property
	 * @type        string
	 */
	@bindable()
	valueProperty: string = 'id';
	/**
	 * @property    display-property
	 * @type        string
	 */
	@bindable()
	displayProperty: any = 'name';
```

**Comment by emcga** [comment]
@adarshpastakia Thanks for your help. I should have looked at the source. My apologies.

**Comment by adarshpastakia** [comment]
@emcga no worries, I'm trying to update the wiki to lookup properties and methods for all elements
