### ISSUE TITLE
Love the features you are adding! Will charts be in v 2.1.4?

### ISSUE THREAD

**Issue by emcga** [adarshpastakia/aurelia-ui-framework#54]
@adarshpastakia I absolutely love where you are taking this framework! Very simple to use and extremely friendly for agile UI development. I have tried other UI frameworks and I just keep coming back to yours. Thank you for your hard work and dedication. I will spread the word about aurelia-ui-framework! Also, when will charts be available? I would love to start incorporating them into my UI design. Thanks again!

**Comment by adarshpastakia** [comment]
@emcga Thanks, really happy that its useful for your projects.

I'm trying to work out simplifying how the chart options and series are passed to the custom element. do you have any preference for a charting library that you use often, i have tried a few different libraries highcharts, chartjs, google material charts, i tried d3 also but found it too complex to implement. finally settled on amCharts, it gives a nice option that allows for exporting charts as images and even the series data as json or csv. 

2.1.4
* Charting elements
* Add time to date input
* Adding a dropdown menu for data-grid button column, useful for displaying multiple options for each record

* Will update the model validation when the aurelia validation is updated. This is an issue i have added on aurelia validation https://github.com/aurelia/validatejs/issues/108 have look if that would be something you might need in your projects

**Comment by emcga** [comment]
@adarshpastakia I have used chartjs in the past on other projects, but I really like the look & feel of amCharts. And I love the fact that it contains built in support for exporting to images, and csv.
