### ISSUE TITLE
support new Aurelia cli

### ISSUE THREAD

**Issue by swalters** [adarshpastakia/aurelia-ui-framework#55]
Can you allow us to use the new cli when including ui-framework as a dependency?  Since NPM doesn't list the dependencies (it relies on jspm), it doesn't currently work.

**Comment by adarshpastakia** [comment]
@swalters i have been wanting to try the new cli and also use webpack instead of jspm, hopefully over the weekend, will update the init script for the skeleton project to allow choosing webpack/jspm and use aurelia cli instead of `aurelia-bundle` gulp task.

if you have tried the new cli before, would be great if you could pass on a few pointers regarding it.

**Comment by swalters** [comment]
I'm not much help :)  This was my first introduction to Aurelia and CLI.  I was trying to create a new project using ui-framework and the CLI.

**Comment by adarshpastakia** [comment]
@swalters i have tried to create a skeleton project for aurelia-cli, however i ran into a few issues. managed to get past the initial hurdle of adding the framework and its dependencies but unfortunately the bundle doesn't seem to work.

Will keep you posted whenever i can resolve the issue, i have commented on an open issue regarding the same in aureia-cli https://github.com/aurelia/cli/issues/212

**Comment by swalters** [comment]
@adarshpastakia Do you see it working like this for a new install in the near future?

npm install aurelia-ui-framework -S
add "aurelia-ui-framework" to aurelia.json dependencies
configure app to load ui-framework plugin

**Comment by adarshpastakia** [comment]
@swalters im not certain of how it might work if the html and js were bundled into a single file that will be loaded by npm, bundling all js code into one file is doable but how it affects the html templates i need to try it to find out. 

however for the moment i did make it a bit simpler by having to add an extra bundle file config in aurelia.json under bundles. having done that the issue currently is `au build` won't bundle external plugin templates and global resources, so i have update the cli skeleton readme with the change, also added a gulp task to copy all relevant files and folders to a dist folder
