### ISSUE TITLE
[Feature Request] enable explicit exclusion of properties from the UIModel functionality

### ISSUE THREAD

**Issue by avrahamcool** [adarshpastakia/aurelia-ui-framework#56]
sometimes we want to add `private` properties to the child that inherits from the `UIModel`,
and we want them to be excluded from `serialization`/`deserialization`/`save`/`discard`/`isDirty` etc..
also: the properties of the `UIModel` himself should always be excluded in that sense.

the `init()` function should receive an optional `Array<string>` of property names to explicitly exclude.

I'm working on this, I will create a PR shortly.

edit: the word `private` is misleading.
I mean that this property should be accessible from the outside of the class, but should be excluded from all `UIModel` logic.

**Comment by adarshpastakia** [comment]
@avrahamcool for that purpose I'm excluding all properties prefixed with a double underscore (__).
I haven't yet had the chance to spend time on the data-model and data-source implementations. maybe we should look into the possibility of adding a decorator '@private' to declare the property definition as 'enumerable: false'

```
Object.defineProperty(this, {
   'propName': {
   writable: true,
   enumerable: false
   })
```

**Comment by avrahamcool** [comment]
indeed I saw that in the code.

but what about the properties that you want to bind into, and you don't want them to be active in the `dirty checking`/`serialization` etc..
it's ugly to have them with `__` in the `html`/`js`.
a cleaner way would be to pass a parameter that tells the model to explicitly exclude them.

a `Private` decorator would suggest that a property is not accessible from outside of that class, in that case that not what we mean.
but the decorator approach is nice and elegant, maybe a different decorator name?

**Comment by adarshpastakia** [comment]
I agree the current approach is a bit ugly but when I added it I was just looking for a quick-fix solution. 

as for the name for a decorator, yes it must not say private instead something to signify non-serializable

**Comment by adarshpastakia** [comment]
Added `@serializable()` decorator for UIModel properties.

Fixed in Version 4
