### ISSUE TITLE
Event subscription question

### ISSUE THREAD

**Issue by firstfocus** [adarshpastakia/aurelia-ui-framework#57]
Hi, first of all, this looks like a great framework library, thanks for all the work on this!
I have a question about the events. I would like to generate a tab strip with closable tabs based on clicks in a tree. As I understand it, the tree component generates UIevents (a shell for eventaggregator) which I can use to build up an array of clicked items for the tab bar, and for use in selecting the tab If I use the generic mouseclick, events are coming through but not for nodeclick, as defined in ui-tree.ts. I cannot find any examples in the for the rest pretty complete docs. What am I missing? Cheers!

```javascript
import {autoinject} from 'aurelia-framework';
import {UIEvent} from "../resources/utils/ui-event";
import {UIUtils} from "../resources/utils/ui-utils";
import {UITreeOptions} from "../resources/utils/ui-tree-model";

import * as _ from "lodash";

@autoinject()

export class TreeComponent {
  tree;
  private subscriber: { dispose: () => void };
  private observer: { dispose: () => void };
  attached() {
        this.subscriber = UIEvent.subscribe('nodeclick', (value) => {
          console.log(JSON.stringify(value));
        });

        this.observer = UIEvent.observe(this.tree, 'nodeclick', (value) => {
          console.log(JSON.stringify(value));
        });
  }

  detached() {
      this.subscriber.dispose();
      this.observer.dispose();
  } 
```

**Comment by adarshpastakia** [comment]
@firstfocus sorry for the late reply, been busy with moving house. anyhow the `nodeclick` is a Dom event and not aggregator broadcast.

```html
<ui-tree nodeclick.trigger="fn($event.detail)"></ui-tree>
```

alternatively you could use `select.trigger` or `checked.trigger` if you are using checkbox tree

**Comment by firstfocus** [comment]
@adarshpastakia no worries! And thanks so much for your reply, of course, I understand now, these are in the DOM so I can make it work, awesome 😃
