### ISSUE TITLE
Updates might take a while

### ISSUE THREAD

**Issue by adarshpastakia** [adarshpastakia/aurelia-ui-framework#61]
Guys,

I'm in the middle on starting my new job and move back home, so the work on the framework might be a bit slow but will try to get all the pull-requests as and when i can. Also the updates for Data-Model and Data-Source will be worked on the `v4.0.0` branch.

Shall keep you guys posted of the progress...

Thanks for all your pull-requests and help on this project 👍

**Comment by avrahamcool** [comment]
good luck with the new job and everything..
