### ISSUE TITLE
Does anyone have a complete working example?

### ISSUE THREAD

**Issue by delebash** [adarshpastakia/aurelia-ui-framework#63]
Your framework looks awesome.

After setting up the example app the css does not seem to be working.  If anyone has a working example they could link to that would be great.

**Comment by avrahamcool** [comment]
in the example, he loads the css in the `index.html` file. (as a regular stylesheet)
https://github.com/adarshpastakia/aurelia-ui-framework/blob/846b8fd4798277bf07f447fc5624d60a4ee69ef9/index.html#L39

but you can also bundle the css and require it to your app.

**Comment by delebash** [comment]
That did it. Thank you for the fix.
