### ISSUE TITLE
Sidebar in app.html not loading routes

### ISSUE THREAD

**Issue by delebash** [adarshpastakia/aurelia-ui-framework#65]
I don't think this is a bug but I can't get it to work right. If you have stackoverflow setup please let me know and I will post it there.

I am trying to setup a layout with sidebar exactly like you have when clicking Get Started.  The only difference is that I do not want to navigate from one view to this one, instead I just want the view to load as is. 

In app.html

```
header...

  <ui-section row-layout animate>
    <ui-sidebar label="Input Elements" collapsible scroll class="ui-hidden-lg-down">
      <ui-menu>
        <ui-menu-item repeat.for="route of router.navigation" href.bind="route.href" active.bind="route.isActive" icon.bind="route.settings.icon" disabled.bind="route.settings.disabled">${route.settings.title || route.title}</ui-menu-item>
      </ui-menu>
    </ui-sidebar>
    <ui-router-view></ui-router-view>
  </ui-section>

footer...
```

app.js has your normal routes setup

The problem is when the page is displayed I see the sidebar and it works but there are no menu items.

I can get this to work using a redirect to a view with this menu but it is a hack and causes a promise timeout.

Thanks

**Comment by avrahamcool** [comment]
can you post a live demo we can test? (gist.run)

I didn't understand what you meant by:

> The only difference is that I do not want to navigate from one view to this one, instead I just want the view to load as is.

**Comment by delebash** [comment]
Attached is what I am trying to do
![ui](https://user-images.githubusercontent.com/2220160/29453736-acfceab2-83d8-11e7-9c0f-38043e00ab70.gif)

**Comment by avrahamcool** [comment]
I do this all the time and it works fine.
can you post a short gist demonstrating your problem?
or upload a small demo project..
so I can help you find the mistake..

**Comment by delebash** [comment]
Thanks for the help.  Attached is a small demo

[testuijs.zip](https://github.com/adarshpastakia/aurelia-ui-framework/files/1234048/testuijs.zip)

If this is not the proper way to accomplish what I showed you, then please let me know how I can change it to the way you normally do things.

To run the app
yarn install
au run

**Comment by avrahamcool** [comment]
You have 2 problems in your router configuration. (not related to UIFramework)
After you fix them - everything works fine.

1. you didn't declare your routes to be visible in the navigation collection.
2. you didn't save a local reference to the router (so you basicly bind your `repeat.for` to `undefined`)
```
export class App {
  configureRouter(config, router) {
    config.title = 'Contacts';
    config.map([
      { route: ['',"hello"],  moduleId: 'hello',   title: 'Hello', nav: true},
      { route: "bye",  moduleId: 'bye',   title: 'Bye', nav: true},
    ]);
    this.router = router;
  }
}
```
instead of: 
```
export class App {
  configureRouter(config, router) {
    config.title = 'Contacts';
    config.map([
      { route: ['',"hello"],  moduleId: 'hello',   title: 'Hello},
      { route: "bye",  moduleId: 'bye',   title: 'Bye'},
    ]);
  }
}
```

**Comment by delebash** [comment]
Thank you very much.  The animation does not seem to be working even though  ` <ui-section row-layout animate>` is set.  I wish I had your programming skills :).  The animation on the pages hello and goodbye

**Comment by avrahamcool** [comment]
you have 2 problems again :)

1. you don't have `aurelia-animator-css` in your project.
1.1 `npm install aurelia-animator-css` (or yarn if you prefer)
1.2. in `main.js` add: `.plugin('aurelia-animator-css')`
1.3 in `aurelia.json` add `"aurelia-animator-css"` to your bundle dependencies.
2. you have the `animate` attribute in the wrong place.
it should be on the actual items that are being swapped.
so in `hello.html` you should have:
```
<template>
  <ui-page animate>
    Hello
  </ui-page>
</template>
```

**Comment by delebash** [comment]
Thank you!
