### ISSUE TITLE
Sidebar disappears when resizing browser to smaller size

### ISSUE THREAD

**Issue by delebash** [adarshpastakia/aurelia-ui-framework#66]
On your demo site click on typography and size the browser down.  It works as expected on the getting started page.

**Comment by avrahamcool** [comment]
for me it works great on all the pages.
are you sure you didn't `click` outside the sidebar by mistake while resizing?
losing the sidebar focus will cause it to close.

FYI: I don't think there is a difference between the pages..
so it's very odd you think it behave differently..

**Comment by delebash** [comment]
Tried on both ff and chrome v 60 same results
Windows 7 x64

![2017-08-19_13-53-49](https://user-images.githubusercontent.com/2220160/29489125-4fc61d22-84e7-11e7-9bc9-580b1dc42347.gif)

**Comment by avrahamcool** [comment]
BTW: I do you create those nice gifs?

oh.. I was looking at the main `menu` [and obviously it's the same for all pages].
now that I understand what to look for I also tried it and I have the same result as you.
the difference between those 2 pages are:

the `Typography` page who is called by the router of `styles/view.html` has a responsive class to hide him when the browser is too small: `class="ui-hidden-lg-down"` as explained [here](https://adarshpastakia.github.io/aurelia-ui-framework/#/grid)

https://github.com/adarshpastakia/aurelia-ui-framework/blob/846b8fd4798277bf07f447fc5624d60a4ee69ef9/src/styles/view.html#L8

and the `Getting started` page who is called by the router of `start/view.html` doesn't.

https://github.com/adarshpastakia/aurelia-ui-framework/blob/846b8fd4798277bf07f447fc5624d60a4ee69ef9/src/start/view.html#L8

**Comment by delebash** [comment]
Got it, thanks. I missed that when looking though the code.  I really love this framework, it is beautiful.  I hope you can keep it up, that is one thing I am worried about. To that end, I posted a link to your site on the aurelia gitter channel.  I was thinking that maybe the official aurelia ux team might look at this as a project they would want to use, since the current project is limited at this moment where as you have a feature complete framework.


ShareX open source


Once launched it will minimize to try, right click and choose capture > screen recording (Gif)


https://getsharex.com/
[https://getsharex.com/img/ShareX_Logo.png]<https://getsharex.com/>

ShareX - Screen capture, file sharing and productivity tool<https://getsharex.com/>
getsharex.com
ShareX is an open source program that lets you take screenshots or screencasts of any selected area with a single key, save them in your clipboard, hard disk or ...




________________________________

**Comment by avrahamcool** [comment]
I'm also in love with the framework, but It's not mine, I'm just a fellow user :)

thanks should go to [Adarsh Pastakia](https://github.com/adarshpastakia)

I also would like if the aurelia team would officially contribute here instead of creating a UI framework from scratch..

**Comment by delebash** [comment]
Yes  @adarshpastakia  has done a great job, and thank you for helping me.

**Comment by adarshpastakia** [comment]
@delebash @avrahamcool guys you are most welcome to use the framework and suggest the updates where needed, as of now i been roped into learning react+redux on my new job and haven't been spending much time on this framework, but will try and keep it updated from time to time.

also a big thanks to @avrahamcool for all his updates and pull requests 👍 

As for the issue, yes i added the responsive hide class for the typography sidebar and overlooked adding it to other sidebars, i guess i was trying to test the class 😃
