### ISSUE TITLE
How do you get the main drawer menu to show the slide menu on the demo site

### ISSUE THREAD

**Issue by delebash** [adarshpastakia/aurelia-ui-framework#67]
On the demo site if you click Buttons item under input elements on the main drawer menu it shows a sidebar menu.

Things tried

My component is located in the core folder called layouts. I have copied the buttons example by adding a view class/html and added the same route info to the app.js only change with my component info file but I keep getting 404.  If I just add the layout route info as a module instead of a redirect then I get my layout page but without the sidebar as expected.

Specifically how is this done in the demo site as each page does not have a drawer menu.

Ultimate goal is to have a drawer main menu that navigates to a page that has the sidebar menu.

![2017-08-19_19-10-54](https://user-images.githubusercontent.com/2220160/29490778-bdd40540-8514-11e7-9935-48fddec179f5.gif)

**Comment by avrahamcool** [comment]
the main page has a drawer:
https://github.com/adarshpastakia/aurelia-ui-framework/blob/846b8fd4798277bf07f447fc5624d60a4ee69ef9/src/app.html#L32

and each inner page has is own sidebar (located at their parent `inputs/view.html`).

https://github.com/adarshpastakia/aurelia-ui-framework/blob/846b8fd4798277bf07f447fc5624d60a4ee69ef9/src/inputs/view.html#L8

**Comment by delebash** [comment]
Yeah I think I have that already but it still wont find route layouts.  

app.js

```
   {
        route: 'core/*path', moduleId: './core/view', title: 'nav.sectionLayouts', nav: false, auth: false, name: 'core'
      },
```

```
{
        route: 'core-layouts', redirect: 'core/layouts', title: 'nav.titleLayouts', nav: true, auth: false, settings: { section: 'nav.sectionCore' }, name: 'layouts'
      },
```

and my file is located in folder core/layouts

**Comment by delebash** [comment]
Thanks for helping  I just re-check the view.js and I forgot to add the route there as well.  I should know about these past couple of issues it's just been the small things that I am missing.
