### ISSUE TITLE
[Chrome Bug] Tooltip is flickering

### ISSUE THREAD

**Issue by avrahamcool** [adarshpastakia/aurelia-ui-framework#71]
it's hard to spot, but if you look closely you'll see that the tooltip flickers right after he opens [Chrome only].
it's caused by the transition on the opacity of the tooltip.
this is a chrome bug that can be fixed by adding `transform: translateZ(0)`.
I don't know why it fixes the issue, but I tested it and it works.

sources:
1. https://stackoverflow.com/a/17353755/1411724
2. https://www.binarymoon.co.uk/2014/02/fixing-css-transitions-in-google-chrome/

i'll show a screen shot shortly.

this is the flickering: pay close attention, the text snaps into place after the transition has finished [500ms]
![broken](https://user-images.githubusercontent.com/5445320/29538202-4fbdaf88-86cd-11e7-89a5-c4447816e485.gif)

after the fix:
![fixed](https://user-images.githubusercontent.com/5445320/29538221-6738e556-86cd-11e7-8bf7-6549fc4ba999.gif)

I'll push a fix shortly.

[should I fix it in `master` or `4.0` or both?]

**Comment by adarshpastakia** [comment]
these fixes we can push to the `master` branch, can merge them into v4 later.
