### ISSUE TITLE
[Bugs] opening lot of `UIDialog`s and in `rtl`

### ISSUE THREAD

**Issue by avrahamcool** [adarshpastakia/aurelia-ui-framework#74]
Bug 1:
when opening a lot of `UIDialog`s, the new ones opens outside the screen.
they cannot be reached by any technique.
[to demonstrate that, I tweeked the code to let me more than 1 instance of the dialog]
![2017-08-24_19-44-49](https://user-images.githubusercontent.com/5445320/29677686-88f9f44e-8904-11e7-944f-8ac877945852.gif)

Bug 2:
maximizing the `UIDialog` in `rtl` also get out of the screen.
![2017-08-24_19-38-31](https://user-images.githubusercontent.com/5445320/29677414-b56ae386-8903-11e7-9de3-8db896d47934.gif)

I tried to fixed it myself, but the code was too hard for me to understand.

**Comment by adarshpastakia** [comment]
@avrahamcool thanks for the update, will look into it. need to recheck how the position coordinates are being calculated. 

got a long weekend off, so will spend time on getting these fixes done and shall plan a version update by Sunday.

**Comment by avrahamcool** [comment]
on that note:
can you add an option to start the dialog as maximized?
can you add an option to start the dialog in a given offset?

you are the best.
