### ISSUE TITLE
inconsistent use of `model` in `UIDialog`

### ISSUE THREAD

**Issue by avrahamcool** [adarshpastakia/aurelia-ui-framework#77]
when calling `UIDialog` without a model,
we still get an empty object in the `activate` hook.
so we can't do a check like `if(model)`.

the reason is because of this line:
https://github.com/adarshpastakia/aurelia-ui-framework/blob/16192b7743a981a8bd43e483df57cf56e5c2f074/src/resources/utils/ui-dialog.ts#L61

why is it necessary?
I've changed it locally on my machine to leave the model as `undefined` and the demo works fine.

I think the behavior should be to not create an empty object when the model was blank.
this is the behavior in all Aurelia components.

can I safely create this change? or am I missing something?

**Comment by adarshpastakia** [comment]
@avrahamcool im not sure why its like that, but if it works fine we can remove it

**Comment by avrahamcool** [comment]
closed by: https://github.com/adarshpastakia/aurelia-ui-framework/commit/721250b78ef54d7b044927a706bc028fbb47a018
