### ISSUE TITLE
[bug] List box selection selects incorrect item

### ISSUE THREAD

**Issue by delebash** [adarshpastakia/aurelia-ui-framework#78]
Chrome 60.0.3112.113 x64, Windows 10

Try selecting different items on the list menu. It  sometimes selects the correct item other times nothing is selected at all.

**Comment by avrahamcool** [comment]
before the fix:

- selecting with the mouse: broken
- selecting with the keys: works
- selecting from other widget: broken

![before](https://user-images.githubusercontent.com/5445320/29971662-bb0bcd9e-8f31-11e7-925f-488dbd3a9cf0.gif)

after the fix:

- selecting with the mouse: works
- selecting with the keys: works but with a little change - when the item is out of view, it will snap to the middle.
- selecting from other widget: works

![after](https://user-images.githubusercontent.com/5445320/29971667-bdf94806-8f31-11e7-8ef4-d9d7c253df84.gif)


I'll post the fix soon.
