### ISSUE TITLE
[Question] Is aurelia-ui-framework mobile ready?

### ISSUE THREAD

**Issue by HamedFathi** [adarshpastakia/aurelia-ui-framework#79]
Hi @adarshpastakia 

Thanks for your great work.

We prefer your framework to aurelia-ux, because of wide range of components and very good appearance but our concern is the mobile platform

Is aurelia-ui-framework mobile ready? Are controls touchable? Can we use your awesome framework on Mobile? Electron? ...

**Comment by adarshpastakia** [comment]
Hi @HamedFathi 

I have not paid much attention at getting the framework mobile ready, certain components like dropdowns will not work well on a mobile, since the overlays won't transform into mobile pickers.

As for electron, I have not tried it myself but if you can bundle an Aurelia application into electron I don't see any issue in using the framework.

**Comment by HamedFathi** [comment]
@adarshpastakia 

Thanks for your clarification

**aurelia-ux :** 
> A user experience framework with higher-level capabilities, designed to bring simplicity and elegance to building cross-device, rich experiences.

Is it possible to transfer your framework to [aurelia-ux](https://github.com/aurelia/ux)? (for supporting any platform)

Do you plan to do this?

**Comment by HamedFathi** [comment]
@adarshpastakia 

Is it possible for you to provide version 4 compatible with mobile?

Otherwise, Do you have any plans for that?

We are very keen to use your awesome framework, but we have problems with mobile

**Comment by adarshpastakia** [comment]
HI @HamedFathi , to make things mobile friendly will need to address quite a few issues. It would be nice to know what problems you are facing, so then we can have a clearer idea what is required to be done.
once the remaining items for v4 are done, maybe we can address the mobile side one at a time

**Comment by avrahamcool** [comment]
@HamedFathi what issue do you currently have with mobile?
if you list them, we can try to address them and maybe make the framework mobile ready. 👍

**Comment by HamedFathi** [comment]
@avrahamcool 

The problem with mobile is very annoying and is visible in the examples of the site is
**DropDown**

If you check these two links on your mobile you can see do not work well.

[lists](https://adarshpastakia.github.io/aurelia-ui-framework/#/lists)
[datetime](https://adarshpastakia.github.io/aurelia-ui-framework/#/datetime)

I did not check other controls.

**Comment by adarshpastakia** [comment]
@HamedFathi all components that have floating containers don't work well on mobile

* button with dropdown
* combo and tag input
* textarea with autocomplete 
* datetime calendar

1. the input issues need to be addressed by using standard dropdown and date input on touch enabled devices
2. dropdown floating containers need to be converted to overlays
3. autocomplete needs to be disabled

**Comment by PeterWone** [comment]
Input type="datetime-local" produces a native picker on all phones.  The quickest fix would be to use that for mobile devices.
