### ISSUE TITLE
changes that need to be transferred to version 4 

### ISSUE THREAD

**Issue by avrahamcool** [adarshpastakia/aurelia-ui-framework#81]
this changes need to be merged to V4.

- [ ] #80  
- [x] #78 
- [x] #77
- [x] #74 
- [x] #73 
- [x] #71

**Comment by adarshpastakia** [comment]
@avrahamcool I have checked in a initial update on v4, we now have it upto date with 3.3.4 which include all these changes.

as for #80 will have to have a look, I too don't remember what exactly is the issue with the lifecycle callbacks
