### ISSUE TITLE
[Question] What features that required drop IE11 support ?

### ISSUE THREAD

**Issue by bigopon** [adarshpastakia/aurelia-ui-framework#84]
I see browser support for IE/Edge is only for Edge13+. May I know for what reasons ?

**Comment by adarshpastakia** [comment]
The only reason for that was I haven't tested it on IE11, so I'm not sure what issues might crop up.

**Comment by avrahamcool** [comment]
an example of something that don't work in IE11:
https://adarshpastakia.github.io/aurelia-ui-framework/#/dialogs

opening the first dialog works fine, closing the dialog fires the events but don't actually close the dialog.

**Comment by jmtrue** [comment]
All works for me on Windows 10 using IE11, even the dialogs. Though, it's pretty slow. So it might seem like it gets stuck loading after hitting the close button. But it will close, for me anyhow. I'm assuming there's a lot of polyfills that are probably grinding down performance. Just a wild guess.
