### ISSUE TITLE
Cannot find Kramed 

### ISSUE THREAD

**Issue by jimboharrison** [adarshpastakia/aurelia-ui-framework#85]
Hi, Im having a problem after having installing the framework. When building the project I get an error thrown in the aurelia-ui-framework.d.ts file on line 13... `_export declare var kramed: KramedStatic;_` . The error reads cannot find KramedStatic yet I assumed this dependency would be pulled with the framework itself? Any one had a similar issue or any ideas ...

**Comment by avrahamcool** [comment]
`kramed` is defined as a dependency.

https://github.com/adarshpastakia/aurelia-ui-framework/blob/2fcc3c11ce268a901c600aec27b3242aecc24d6e/package.json#L61

you are missing the typings definition.
have you done those steps?
https://adarshpastakia.github.io/aurelia-ui-framework/#/start/prereq

there is an open request (by me, yayy) to use @types instead of typings.
https://github.com/adarshpastakia/aurelia-ui-framework/issues/72

**Comment by avrahamcool** [comment]
same as https://github.com/adarshpastakia/aurelia-ui-framework/issues/22

**Comment by Mobe91** [comment]
@avrahamcool I have installed the kramed typings (`typings/modules/kramed` and `node_modules/aurelia-ui-framework/dist/typings/kramed.d.ts` exist) but compilation still fails with the same error.

**Comment by pakkle** [comment]
@avrahamcool, @Mode91

To fix KamedStatic, add manually kramed.d.ts to your project from aurelia_ui_framework_project (https://github.com/adarshpastakia/aurelia-ui-framework), located at src/resources/typings

You will need to add return type to SetOption as well (at least with the latest Aurelia and Typescript):

setOptions(options: any): any;

**Comment by charlessolar** [comment]
To my knowledge of definition files, there is no reason for aurelia-ui-framework.d.ts to export (or import) any of this
```
import 'lodash';
import 'moment';
import 'numeral';
import * as mm from "moment";
export declare var _: any;
export declare var kramed: KramedStatic;
export declare var moment: typeof mm;
export declare var numeral: any;
```

You should only export your library's stuff - I can't think of any reason these lines would be necessary but you'll know best

**Comment by avrahamcool** [comment]
@volak I agree. 
@adarshpastakia can we fix that for the next release?
