### ISSUE TITLE
dist/typings/aurelia-ui-framework.d.ts contains invalid paths

### ISSUE THREAD

**Issue by Mobe91** [adarshpastakia/aurelia-ui-framework#87]
When importing typings from aurelia-ui-framework using its supplied typings.json, I receive erros because the following imports in `dist/typings/aurelia-ui-framework.d.ts` refer to invalid paths:
```ts
import './libs/countries';
import './libs/currencies';
import './libs/filetypes';
import './libs/phonelib';
import './libs/window';
import './attributes/ui-badge';
```

**Comment by adarshpastakia** [comment]
Same issue as #85
