### ISSUE TITLE
Aurelia typescript sekelton with aurelia-ui-framework

### ISSUE THREAD

**Issue by Mobe91** [adarshpastakia/aurelia-ui-framework#88]
Hi, I am trying to get the [Aurelia typescript sekelton](https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-typescript) to work with aurelia-ui-framework. I tried to follow the README instructions in the [aurelia-ui-framework starter project](https://www.dropbox.com/sh/1b2ytrrk0n8wpva/AAB7qLUK5huA9ssd5wpwDtSha?dl=0) but I could not get it to work so far. 

Currently, I am stuck with the following error during bundling:
`skeleton-typescript/node_modules/aurelia-ui-framework/dist/typings/aurelia-ui-framework.d.ts(7,28): error TS2304: Cannot find name 'KramedStatic'.`

Since I am new in Aurelia and aurelia-ui-framework, I would appreciate some help. Please find the [project](https://github.com/adarshpastakia/aurelia-ui-framework/files/1412200/skeleton-typescript.zip) attached.

**Comment by avrahamcool** [comment]
same as https://github.com/adarshpastakia/aurelia-ui-framework/issues/85.

reopen the issue if you still encounter a problem.
