### ISSUE TITLE
[Bug] ui-input readonly and disabled bindings

### ISSUE THREAD

**Issue by avrahamcool** [adarshpastakia/aurelia-ui-framework#89]
Issue 1:
if I want an `<ui-input>` to be always `readonly` or always `disabled` I want to do:
`<ui-input readonly></ui-input>`  and `<ui-input disabled></ui-input>` .

but currently I have to do:
`<ui-input readonly="true"></ui-input>`  and `<ui-input disabled="true"></ui-input>` .
or:
`<ui-input readonly="false"></ui-input>`  and `<ui-input disabled="false"></ui-input>` .

notice:
the example with the `false` is not a bug, because the string `"false"` evaluates to a `truthy` value in javascript. this can be also shown in the standard chrome implementation for `readonly` and `disabled`.
https://jsfiddle.net/eabgqxt3/

Issue 2:
the binding is resolved to `true` only for values that are one of the following:
`true`, `yes`, `y`, `1`, `on`.
but in javascript (and in all aurelia) - all the thing that are `truthy` are working in boolean bindings.
so we should also support that.

the problem is you are using this `isTrue` function, instead of checking for regular javascript `truthy` value.

```
isTrue
ƒ (e){return/^(true|yes|1|y|on)$/i.test(e)}
```

https://github.com/adarshpastakia/aurelia-ui-framework/blob/ade5a80a12c807f51ab05609c2d524c119b9614e/src/resources/elements/inputs/ui-input.ts#L27

https://github.com/adarshpastakia/aurelia-ui-framework/blob/ade5a80a12c807f51ab05609c2d524c119b9614e/src/resources/elements/inputs/ui-input.ts#L31

can I change that behaviour? or it was on purpose?

**Comment by avrahamcool** [comment]
The same issue is also relevant for `ui-combo` and probably more.
I'll patch them as well soon.

**Comment by avrahamcool** [comment]
@adarshpastakia 
The problem is in everything that uses `isTrue` in bindings.
can I change this function to do a simple `return !!value`? I am afraid of breaking something in the library.
or fix each input individually?

**Comment by adarshpastakia** [comment]
@avrahamcool i suppose for disable/readonly property we can remove the isTrue
